sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rcalvoquintero/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rcalvoquintero/docker-react npm run test