language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t rcalvoquintero/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rcalvoquintero/docker-react npm run test -- --coverage